name: Deploy Weather overlay

on: 
  push:
    branches: [main]
    
jobs:
  my-job:
    name: Deploy weather overlay app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install node dependencies
        run: 
          npm install
          npm run build --if-present
      - name: Deploy to de-weather-overlay.surge.sh
        uses: dswistowski/surge-sh-action@v1.0.2
        with:
          domain: 'de-weather-overlay.surge.sh'
          project: './dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
