name: Deploy Weather overlay

on: 
  push:
    branches: 
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  my-job:
    name: Deploy weather overlay app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Create dist directory
        run: mkdir dist
      - name: Install node dependencies
        run: 
          npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_APPID: "788f836079b901cdd86a04b293dece10"
          envkey_VITE_API: "WeatherAPI"
      - name: Build dist
        run:
          npm run build
      - name: List dist files
        run: ls dist
      - name: Deploy to de-weather-overlay.surge.sh
        uses: dswistowski/surge-sh-action@v1.0.2
        with:
          domain: 'de-weather-overlay.surge.sh'
          project: './dist'
          login: detheridge02@gmail.com
          token: 12d3416a0ed57777e73675a9c081936b
